git: relative URL support

diff --git a/packages/git b/packages/git
--- a/packages/git
+++ b/packages/git
@@ -2,20 +2,40 @@
 package_name=git
 package_version=2.7.3
 tarball_suffix=xz
-url=http://mirrors.tassig.com/git/
 build_dependencies="zlib libressl curl perl gettext expat"
 iscustombuild=1
+no_check=1 # TODO: 6 tests failed
 
 custombuild(){
-	package_fullname=$package_name-$package_version
-	package_tarball_name=$package_fullname.tar.$tarball_suffix
-	wget $url/$package_tarball_name
-	tar xvf $package_tarball_name
-	cd $package_fullname/
-	LDFLAGS="-L/opt/libressl/lib -Wl,-rpath-link=/opt/libressl/lib"   ./configure --prefix=/opt/$package_fullname --with-openssl=/opt/libressl --with-zlib=/opt/zlib --with-curl=/opt/curl --with-perl=/bin/perl --with-expat=/opt/expat   # LDFLAGS fixes a bug in a git executable linkage
-	make -j 
-	make install
-	ln -s /opt/$package_fullname /opt/$package_name
-	ln -s /opt/$package_name/bin/* /bin/
-	cd ..
+    rm -rf builddir
+    mkdir -p builddir   # do everything in builddir for tidiness
+    cd builddir
+    if [ "$url" == "" ]; then
+        # if no absolute $url defined, then assume, that we have relative url 
+        # $rel_url
+        url=$mirror_prefix/$rel_url
+    fi
+    wget -O archive $url
+    tar xvf archive
+    rm archive
+    cd *   # cd into the package directory
+
+	LDFLAGS="-L$installdirectory/libressl/lib -Wl,-rpath-link=$installdirectory/libressl/lib"   ./configure --prefix=$installdirectory/$package_fullname --with-openssl=$installdirectory/libressl --with-zlib=$installdirectory/zlib --with-curl=$installdirectory/curl --with-perl=/bin/perl --with-expat=$installdirectory/expat   # LDFLAGS fixes a bug in a git executable linkage
+
+    make -j
+    if test -z $no_check   # run the make check, unless $no_check is set for 
+                           # this package definition
+    then make -j check || make -j test
+    fi
+    make install
+    ln -sv $installdirectory/$package_fullname $installdirectory/$package_name
+    ln -sv $installdirectory/$package_name/bin/* /bin/ || true   # don't crash 
+                                            # if the links are already there
+    if [ -d "$installdirectory/$package_name/lib/pkgconfig" ]; then
+        ln -svf $installdirectory/$package_name/lib/pkgconfig/* \
+        $installdirectory/pkgconf/lib/pkgconfig/   # install pkg-config files
+    fi
+    cd ../..
+    rm -r builddir
+
 }
