glib: relative URL support

diff --git a/packages/glib b/packages/glib
--- a/packages/glib
+++ b/packages/glib
@@ -1,28 +1,43 @@
 package_name=glib
 package_version=2.48.1
 tarball_suffix=xz
-url=http://mirrors.tassig.com/$package_name/$package_name-$package_version.tar.$tarball_suffix
 build_dependencies="python2 libffi pcre" # python is needed for proper installation
 iscustombuild=1
+no_check=1 # TODO: 14 tests failed
 
 custombuild(){
-	package_fullname=$package_name-$package_version
-	wget -O archive $url
-	tar xvf archive
-	rm archive
-	cd $package_name*
+    rm -rf builddir
+    mkdir -p builddir   # do everything in builddir for tidiness
+    cd builddir
+    if [ "$url" == "" ]; then
+        # if no absolute $url defined, then assume, that we have relative url 
+        # $rel_url
+        url=$mirror_prefix/$rel_url
+    fi
+    wget -O archive $url
+    tar xvf archive
+    rm archive
+    cd *   # cd into the package directory
 
-	pwd="`pwd`"
-	for p in "$pwd"/../packages/$package_name-*.patch; do
+	for p in ../../packages/$package_name-*.patch; do
 		patch -p1 < $p
 	done
 
-	LDFLAGS="-Wl,-rpath=/opt/pcre/lib/ -Wl,-rpath=/opt/libffi/lib64 -Wl,-rpath=/opt/zlib/lib"  ./configure --prefix=/opt/$package_fullname/   # apparently a bug in configure
-	make -j
-	# TODO: make check
-	make install
-	ln -sv /opt/$package_fullname /opt/$package_name
-	ln -sv /opt/$package_name/bin/* /bin/ || true
-	ln -svf /opt/$package_name/lib/pkgconfig/* /opt/pkgconf/lib/pkgconfig/   # some packages rely on pkgconf
-	cd ..
+	LDFLAGS="-Wl,-rpath=$installdirectory/pcre/lib/ -Wl,-rpath=$installdirectory/libffi/lib64 -Wl,-rpath=$installdirectory/zlib/lib"  ./configure --prefix=$installdirectory/$package_fullname/   # apparently a bug in configure
+    make -j
+    if test -z $no_check   # run the make check, unless $no_check is set for 
+                           # this package definition
+    then make -j check || make -j test
+    fi
+    make install
+    ln -sv $installdirectory/$package_fullname $installdirectory/$package_name
+    ln -sv $installdirectory/$package_name/bin/* /bin/ || true   # don't crash 
+                                            # if the links are already there
+    if [ -d "$installdirectory/$package_name/lib/pkgconfig" ]; then
+        ln -svf $installdirectory/$package_name/lib/pkgconfig/* \
+        $installdirectory/pkgconf/lib/pkgconfig/   # install pkg-config files
+    fi
+    cd ../..
+    rm -r builddir
+
 }
