bluez: sync custombuild with defaultbuild

diff --git a/packages/libical b/packages/libical
--- a/packages/libical
+++ b/packages/libical
@@ -3,6 +3,12 @@ package_version=2.0.0
 tarball_suffix=gz
 build_dependencies=cmake
 iscustombuild=1
+no_check=1
+# The following tests FAILED:
+#	  2 - recur (Failed)
+#	  4 - testvcal (OTHER_FAULT)
+#	  6 - timezones (Failed)
+
 
 ##########################
 #
@@ -15,32 +21,28 @@ iscustombuild=1
 
 # custom build because using cmake
 custombuild(){
-        rm -rf builddir
-        mkdir -p builddir
-
-        cd builddir
-
-        wget $url -O archive
-        tar -xf archive
-        rm -f archive
-        cd *
-
-	cmake -DCMAKE_INSTALL_PREFIX=/opt/$package_name-$package_version  -DCMAKE_RELEASE_TYPE=Release -DSTATIC_ONLY=true
-        make
-        make install
-
-        cd ../..
-        rm -rf builddir
-
-        ln -sv /opt/$package_name-$package_version /opt/$package_name
-        ln -svf /opt/$package_name-$package_version/lib/pkgconfig/* /opt/pkgconf/lib/pkgconfig/
-
-	ln -sv $installdirectory/$package_name/bin/* /bin/ || true   # don't crash 
-											# if the links are already there
+	rm -rf builddir
+	mkdir -p builddir   # do everything in builddir for tidiness
+	cd builddir
+	wget -O archive $url
+	tar xvf archive
+	rm archive
+	cd *   # cd into the package directory
+	cmake -DCMAKE_INSTALL_PREFIX=$installdirectory/$package_fullname/ -DCMAKE_RELEASE_TYPE=Release -DSTATIC_ONLY=true
+	ncpu=`cat /proc/cpuinfo | grep processor | wc -l`
+	make -j$ncpu
+	if test -z $no_check   # run the make check, unless $no_check is set for this package definition
+	then make -j$ncpu check || make -j$ncpu test
+	fi
+	make install
+	ln -sv $installdirectory/$package_fullname $installdirectory/$package_name
+	ln -sv $installdirectory/$package_name/bin/* /bin/ || true   # don't crash if the links are already there
 	if [ -d "$installdirectory/$package_name/lib/pkgconfig" ]; then
-		ln -svf $installdirectory/$package_name/lib/pkgconfig/* \
+        	ln -svf $installdirectory/$package_name/lib/pkgconfig/* \
 		$installdirectory/pkgconf/lib/pkgconfig/   # install pkg-config files
 	fi
+	cd ../..
+	rm -r builddir
 }
 
 
